config/routes.rb
Rails.application.routes.draw do

  #rootから始める
  root to: 'tasks#index'
  
  resources :tasks
  
  #UserのRoute追加
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  #get 'users/:id', to: 'users#show', as: 'user'
  #asを利用してFile_pathを変更できる?

  #sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 } #不要, uniqueness: true
  validates :status, presence: true, length: { maximum: 10 }
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email,password)
      flash[:success] = 'Hi!! Welcome back here!!!'
      redirect_to root_url
    else
      flash.now[:danger] = 'Ops,,,, Failed!!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Bye. See you again!'
    redirect_to root_url
  end
  
  private
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #Login
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in #全てのアクションでログイン必須！, only: [:show, :new, :edit]
  #correct_Userがあり@taskの二重定義になっているため不要
  #before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  #include SessionsHelper
  
  def index
      @tasks = current_user.tasks.order(id: :desc).page(params[:page]).per(10)
  end

  def show
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = 'Registered New Task!!'
      redirect_to tasks_url
    else
      flash.now[:danger] = 'Failure Registration...'
      render :new
    end
    
    
  end
  
  def edit
  end

  def update
    
    if @task.update(task_params)
      flash[:success] = 'Modified your Task!!'
      redirect_to task_path(@task)
    else
      flash.now[:danger] = 'Failure Updating...'
      render :new
    end
  end

  def destroy
    @task.destroy
    
    flash[:success] = 'Task has deleted!'
    redirect_to tasks_url
  end
  
  private
  
  #correct_Userがあり@taskの二重定義になっているため不要
  #def set_task
  #  @task = Task.find(params[:id])
  #end
  
  #Current_User Only
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
  #strong parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'Signed Up!!'
      #セッション構築
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash.now[:danger] = 'Failed,,,,'
      render :new
    end
  end
  
  private
  #未使用のため削除
  #def set_user
  #  @user = User.find(params[:id])
  #end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_msg.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>"><%= msg %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <!--ロゴとかを置くNavbar-brand-->
    <a class="navbar-brand" href="/">Task List</a>
    
    <!--Humberger button-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!--Menu-->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="navbar-item"><%= link_to 'New Task', new_task_path, class: 'nav-link' %></li>
          <!--課題のため削除
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"></li>
              <li class="dropdown-diviber"></li>
              <li class="dropdown-item"></li>
            </ul>
          </li>
          -->
          <li class="navbar-item"><%= link_to 'Log Out', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="navbar-item"><%= link_to 'Sign Up', signup_path, class: 'nav-link' %></li>
          <li class="navbar-item"><%= link_to 'Log In', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
    
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="ja">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
 
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class='container'>
      <%= render 'layouts/flash_msg' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: task, local: true) do |f| %>
    
      <% if task.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-group">
        <%= f.label :content, 'Task Detail' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :status, 'Task status' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>
      <%= f.submit 'UP as Task', class: 'btn btn-primary' %>
      
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<H1>Edit your Task</H1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<% if logged_in? %>  
  <h1>Hi! <%= current_user.name %>, This is TASK LIST!!</h1>

  <% if @tasks.any? %>
    <table class="table table-striped table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th>id</th>
          <th>Task</th>
          <th>status</th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= link_to task.id, task_path(task.id) %></td>
            <td><%= task.content %></td>
            <td><%= task.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <div>
      <%= paginate @tasks %>
    </div>
  <% end %>
  
  <%= link_to 'New Task Registration', new_task_path, class: "btn btn-primary" %>
  
<% else %>
  
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel"　data-interval="5">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="center jumbotron" style="background-color:#4b0082;">
          <div class="text-center pb-4">
            <h1 class="text-white">Welcome to the Task List1<br></h1>
          </div>
        </div>
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
        <div class="center jumbotron" style="background-color:#CFD8DC;">
          <div class="text-center pb-4">
            <h1>Welcome to the Task List2</h1>
          </div>
        </div>
        <div class="carousel-caption d-none d-md-block text-black">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
      <div class="carousel-item">
        <div class="center jumbotron" style="background-color:#00ff00;">
          <div class="text-center pb-4">
            <h1>Welcome to the Task List3</h1>
          </div>
        </div>
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  
  <div class="text-center">
    <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<H1>Create New Task</H1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>Id : <%= @task.id %> Detail Page</h1>



<table class="table table-striped table-bordered table-hover">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>Task</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>status</th>
    <td><%= @task.status %></td>
  </tr>
  <tr>
    <th>Registered at</th>
    <td><%= @task.created_at.strftime('%Y/%m/%d') %><br><%= time_ago_in_words(@task.created_at) %> before</td>
  </tr>
</table>


<%= link_to 'Edit your Task', edit_task_path(@task.id), class: 'btn btn-dark' %>
<%= link_to 'Delete this task', @task, method: :delete, data: { confirm: 'Are you sure to delete?' }, class: 'btn btn-danger' %>

app/views/users/new.html.erb
<h1 class="text-center">Sign Up!!</h1>

<div class="row justify-content-md-center">
  <div class="col-md-6">
    
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %> 
    <!--f.object は　@userのこと-->
    
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div> 
      
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>      
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'Password Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign Up',class: 'btn btn-primary btn-block' %>
      
    <% end %>
    
    <p class="mt-3">You have Account? <%= link_to 'Log In Now!!', login_path %></p>
  </div>
</div>